[theme]
# Dark mode primary color (blue accent)
primaryColor = "#4A90E2"

# Dark background for the main app
backgroundColor = "#1E1E1E"

# Darker background for widgets
secondaryBackgroundColor = "#2E2E2E"

# Light text for readability on dark background
textColor = "#E0E0E0"

# Use Poppins font for a modern look
font = "Poppins"